version: '3.8'

services:
  caddy-jellywol:
    image: ghcr.io/stoufiler/caddy-jellywol:latest
    container_name: caddy-jellywol
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/bin/caddy", "version"]
      interval: 30s
      timeout: 3s
      retries: 3
    environment:
      TZ: Europe/Paris
